version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_USER: itsm
      MYSQL_PASSWORD: admin@123
      MYSQL_DATABASE: itsm_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
